# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Tool_Modularization

pool:
  vmImage: macos-latest

steps:
- script: javac *.java
  displayName: 'compile script'

- script: jar cfm .jar manifest.txt *.class
  displayName: 'generate jar file'
